/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.21
 * Generated at: 2019-07-09 14:42:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class acessorio_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/topo.jsp", Long.valueOf(1562683199387L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- JQuery -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"https://use.fontawesome.com/releases/v5.0.8/js/all.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Adicionar arquivo CSS externo -->\r\n");
      out.write("    <link href=\"estilos.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!--Ícone - Logo-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"favicon.ico.ico\" type=\"image/x-icon\" />\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    // If user clicks anywhere outside of the modal, Modal will close\r\n");
      out.write("\r\n");
      out.write("    var modal = document.getElementById('modal-wrapper');\r\n");
      out.write("    window.onclick = function (event) {\r\n");
      out.write("        if (event.target == modal) {\r\n");
      out.write("            modal.style.display = \"none\";\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!--Cabeçalho-->\r\n");
      out.write("    <header class=\"menu-principal\">\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"header-1\">\r\n");
      out.write("                <div class=\"logo\">\r\n");
      out.write("                    <img src=\"imagens/logo-pegasus.png\" />\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("       \r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\r\n");
      out.write("            aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <!--Itens de navegação-->\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("            <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"index.jsp\">Início <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <!--Dropdown-->\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\"\r\n");
      out.write("                        data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                        Serviços</a>\r\n");
      out.write("                    <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"BanhoEtosa.jsp\">Banho e tosa</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\"\r\n");
      out.write("                        data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                        Produtos\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"alimento.jsp\">Alimentação</a>\r\n");
      out.write("                        <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"higiene.jsp\">Higiene</a>\r\n");
      out.write("                        <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"acessorio.jsp\">Acessórios</a>\r\n");
      out.write("                        <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"farmacia.jsp\">Farmácia</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <!--Fixos-->\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"CadastroCliente.jsp\">Cadastro <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#adocao\">Adoção <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"avaliacao.html\">Avaliação <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#quemsomos\">Quem somos? <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#contato\">Contato <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");

try{
		
		//Obter a mensagem
		String mensagem = request.getParameter("mensagem");
	
		//Tipos de mensagem
		switch(mensagem){
			case "falhaLogin":
				out.print("<div class='mensagem'>Usuário ou senha incorretos</div>");
			break;
			case "falhaSessao":
				out.print("<div class='mensagem'>Realize o login</div>");
			break;
		}
	}catch(Exception erro){}
	


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- PopUp -->\r\n");
      out.write("\r\n");
      out.write("<button class=\"btn btn-secondary my-2 my-sm-0\"\r\n");
      out.write("    onclick=\"document.getElementById('modal-wrapper').style.display='block'\"\r\n");
      out.write("    style=\"width:200px; margin-top:200px; margin-left:160px;\"><i class=\"fas fa-user\"></i>\r\n");
      out.write("    Fazer login</i></button>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("<div id=\"modal-wrapper\" class=\"modal\">\r\n");
      out.write("\r\n");
      out.write("    <form class=\"modal-content animate\" action=\"/action_page.php\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"imgcontainer\">\r\n");
      out.write("            <span onclick=\"document.getElementById('modal-wrapper').style.display='none'\" class=\"close\"\r\n");
      out.write("                title=\"Fechar PopUp\">×</span>\r\n");
      out.write("            <img src=\"img/icone.jfif    \" alt=\"Avatar\" class=\"avatar\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <input type=\"text\" placeholder=\"Nome de usuário\" name=\"uname\">\r\n");
      out.write("            <input type=\"password\" placeholder=\"Senha\" name=\"psw\">\r\n");
      out.write("            <button type=\"submit\">Login</button>\r\n");
      out.write("            <input type=\"checkbox\" style=\"margin:26px 30px;\"> Remember me\r\n");
      out.write("            <a href=\"#\"\r\n");
      out.write("                style=\"text-decoration:none; float:right; margin-right:34px; margin-top:26px;\">Esqueceu a senha?</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Acessórios Pet</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- JQuery -->\r\n");
      out.write("\r\n");
      out.write("<!-- Fotorama -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Adicionar arquivo CSS -->\r\n");
      out.write("<link href=\"estilos.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!--Cabeçalho-->\r\n");
      out.write("\t<header class=\"menu-principal\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"header-1\">\r\n");
      out.write("\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t<img src=\"imagens/Logo.png\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"redes-sociais\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Banner -->\r\n");
      out.write("\t<section class=\"fotorama\" data-width=\"100%\" data-loop=\"true\"\r\n");
      out.write("\t\tdata-autoplay=\"2500\" data-stopautoplayontouch=\"false\"\r\n");
      out.write("\t\tdata-transition=\"crossfade\">\r\n");
      out.write("\t\t<img src=\"imagens/img1.jpg\"> <img src=\"imagens/img2.jpg\">\r\n");
      out.write("\t\t<img src=\"imagens/img3.jpg\">\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Título de produto 1 -->\r\n");
      out.write("\t<div class=\"menu-produto\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<H3>Comedouros e Bebedouros</H3>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Adicionar produtos -->\r\n");
      out.write("\t<div class=\"card-deck\">\r\n");
      out.write("\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t<img class=\"card-img-top\" src=\"imagens/Comedouro1-01.png\"\r\n");
      out.write("\t\t\t\talt=\"Imagem de capa do card\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h5 class=\"card-title\">Bebedouro automático</h5>\r\n");
      out.write("\t\t\t\t<p class=\"font-weight-bold\">Marca: Idealdog.</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t- Indicado para cães e gatos. <br>- Combina praticidade e\r\n");
      out.write("\t\t\t\t\tbeleza. <br>- Desenvolvido para pets que ficam sozinhos por\r\n");
      out.write("\t\t\t\t\tlongos períodos. <br>- Tem capacidade para 3 litros.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<h5 class=\"font-weight-bold\" style=\"color: rgb(195, 93, 36)\">R$37,99</h5>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-primary\"\r\n");
      out.write("\t\t\t\t\tonClick=\"AddCarrinho('Bebedouro automático','1','37.99','1')\">Comprar</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t<img class=\"card-img-top\" src=\"imagens/Comedouro2-01.png\"\r\n");
      out.write("\t\t\t\talt=\"Imagem de capa do card\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h5 class=\"card-title\">Bebedouro porta remédio</h5>\r\n");
      out.write("\t\t\t\t<p class=\"font-weight-bold\">Marca: Mr. Pet</p>\r\n");
      out.write("\t\t\t\t<p class=\"card-text\">Se o seu pássaro precisa tomar alguma\r\n");
      out.write("\t\t\t\t\tmedicação, utilizar o bebedouro pode ser a melhor forma de dar o\r\n");
      out.write("\t\t\t\t\tremédio a ele. O Bebedouro com Porta Remédio Mr. Pet Passáros é\r\n");
      out.write("\t\t\t\t\tideal para a manipulação de medicamentos e transporte. Fácil\r\n");
      out.write("\t\t\t\t\tfixação na gaiola e por ser de plástico a sua higienização é\r\n");
      out.write("\t\t\t\t\tprática e rápida.</p>\r\n");
      out.write("\t\t\t\t<h5 class=\"font-weight-bold\" style=\"color: rgb(195, 93, 36)\">R$2,99</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-primary\"\r\n");
      out.write("\t\t\t\t\tonClick=\"AddCarrinho('Bebedouro porta remédio','1','2.99','2')\">Comprar</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t<img class=\"card-img-top\" src=\"imagens/Comedouro3-01.png\"\r\n");
      out.write("\t\t\t\talt=\"Imagem de capa do card\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h5 class=\"card-title\">Comedouro Snoopy</h5>\r\n");
      out.write("\t\t\t\t<p class=\"font-weight-bold\">Marca: Zooz Pets</p>\r\n");
      out.write("\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t- Indicado para cães. <br>- Super leve e fácil de higienizar.\r\n");
      out.write("\t\t\t\t\t<br>- Com antiderrapante que evita que seu pet arraste o\r\n");
      out.write("\t\t\t\t\tcomedouro por todo lado. <br>- Disponível nos tamanhos P, M e\r\n");
      out.write("\t\t\t\t\tG.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<h5 class=\"font-weight-bold\" style=\"color: rgb(195, 93, 36)\">R$59,99</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");

				if (session.getAttribute("usuario") == null)
			
      out.write("\r\n");
      out.write("\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-primary\"\r\n");
      out.write("\t\t\t\t\tonClick=\"AddCarrinho('Comedouro Snoopy','1','59.99','3')\">Comprar</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<!-- Título de produto 2 -->\r\n");
      out.write("\t<div class=\"menu-produto\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<H3>Transporte</H3>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Adicionar produtos -->\r\n");
      out.write("\t<div class=\"card-deck\">\r\n");
      out.write("\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t<img class=\"card-img-top\" src=\"imagens/Transporte1-01.png\"\r\n");
      out.write("\t\t\t\talt=\"Imagem de capa do card\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h5 class=\"card-title\">Caixa de transporte luxo</h5>\r\n");
      out.write("\t\t\t\t<p class=\"font-weight-bold\">Marca: Furacão.</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t- Indicado para cães e gatos. <br>- Tem longa durabilidade. <br>-\r\n");
      out.write("\t\t\t\t\tFácil de carregar. <br>- Possui um sistema fechamento rápido.\r\n");
      out.write("\t\t\t\t\t<br>- Disponível nos tamanhos 2 e 3.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<h5 class=\"font-weight-bold\" style=\"color: rgb(195, 93, 36)\">R$79,90</h5>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"btn btn-primary\">Comprar</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t<img class=\"card-img-top\" src=\"imagens/Transporte2-01.png\"\r\n");
      out.write("\t\t\t\talt=\"Imagem de capa do card\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h5 class=\"card-title\">Bolsa Griff Dog</h5>\r\n");
      out.write("\t\t\t\t<p class=\"font-weight-bold\">Marca: Griff Dog.</p>\r\n");
      out.write("\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t- Indicada para cães e gatos. <br>- Ideal para os pets de\r\n");
      out.write("\t\t\t\t\tpequeno e médio porte. <br>- Proporciona mais segurança e\r\n");
      out.write("\t\t\t\t\tconforto aos pets. <br>- Feita de camurça. <br>- Fácil de\r\n");
      out.write("\t\t\t\t\tcarregar.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<h5 class=\"font-weight-bold\" style=\"color: rgb(195, 93, 36)\">R$102,90</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"btn btn-primary\">Comprar</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t<img class=\"card-img-top\" src=\"imagens/Transporte3-01.png\"\r\n");
      out.write("\t\t\t\talt=\"Imagem de capa do card\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h5 class=\"card-title\">Capa protetora de banco</h5>\r\n");
      out.write("\t\t\t\t<p class=\"font-weight-bold\">Marca: Chalesco</p>\r\n");
      out.write("\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t- Indicada para proteção de estofado de carros. <br>- Protege\r\n");
      out.write("\t\t\t\t\to banco traseiro do automóvel. <br>- Possui abertura para\r\n");
      out.write("\t\t\t\t\tacesso ao cinto de segurança. <br>- Evita o acumulo de pelos\r\n");
      out.write("\t\t\t\t\tno interior do veículo. <br>- Seu pet seguro e seu carro\r\n");
      out.write("\t\t\t\t\tsempre protegidos durante os passeios.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<h5 class=\"font-weight-bold\" style=\"color: rgb(195, 93, 36)\">R$59,99</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"btn btn-primary\">Comprar</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<!-- Título de produto 3 -->\r\n");
      out.write("\t<div class=\"menu-produto\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<H3>Caminhas</H3>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Adicionar produtos -->\r\n");
      out.write("\t<div class=\"card-deck\">\r\n");
      out.write("\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t<img class=\"card-img-top\" src=\"imagens/Cama1-01.png\"\r\n");
      out.write("\t\t\t\talt=\"Imagem de capa do card\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h5 class=\"card-title\">Cama M1 Urban Puppy</h5>\r\n");
      out.write("\t\t\t\t<p class=\"font-weight-bold\">Marca: Urban Puppy.</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t- Indicado para cães e gatos. <br>- Enchimento removível. <br>-\r\n");
      out.write("\t\t\t\t\tFibra siliconada. <br>- Estampa exclusiva. <br>- Super\r\n");
      out.write("\t\t\t\t\tconfortável e quentinha.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<h5 class=\"font-weight-bold\" style=\"color: rgb(195, 93, 36)\">R$129,99</h5>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"btn btn-primary\">Comprar</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t<img class=\"card-img-top\" src=\"imagens/Cama2-01.png\"\r\n");
      out.write("\t\t\t\talt=\"Imagem de capa do card\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h5 class=\"card-title\">Bolsa Pawise Bloster</h5>\r\n");
      out.write("\t\t\t\t<p class=\"font-weight-bold\">Marca: Pawise.</p>\r\n");
      out.write("\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t- Indicada para gatos. <br>- Super aconchegante. <br>-\r\n");
      out.write("\t\t\t\t\tDesign fofo. <br>- Seu amigo mais confortável na hora do\r\n");
      out.write("\t\t\t\t\tdescanso. <br>- Material: Poliéster.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<h5 class=\"font-weight-bold\" style=\"color: rgb(195, 93, 36)\">R$99,99</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"btn btn-primary\">Comprar</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t<img class=\"card-img-top\" src=\"imagens/Cama3-01.png\"\r\n");
      out.write("\t\t\t\talt=\"Imagem de capa do card\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h5 class=\"card-title\">Capa Siesta Deluxe</h5>\r\n");
      out.write("\t\t\t\t<p class=\"font-weight-bold\">Marca: Ferplast</p>\r\n");
      out.write("\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t- Indicada para cachorros e gatos. <br>- Feita de plástico\r\n");
      out.write("\t\t\t\t\tresistente e antiderrapante. <br>- Conta com encosto para a\r\n");
      out.write("\t\t\t\t\tcabeça do pet. <br>- Proporciona mais conforto. <br>-\r\n");
      out.write("\t\t\t\t\tDisponível em 6 tamanhos.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<h5 class=\"font-weight-bold\" style=\"color: rgb(195, 93, 36)\">R$69,99</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"btn btn-primary\">Comprar</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<!-- Título de produto 4 -->\r\n");
      out.write("\t<div class=\"menu-produto\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<H3>Casinhas, gaiolas e aquários</H3>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Adicionar produtos -->\r\n");
      out.write("\t<div class=\"card-deck\">\r\n");
      out.write("\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t<img class=\"card-img-top\" src=\"imagens/Casinha1-01.png\"\r\n");
      out.write("\t\t\t\talt=\"Imagem de capa do card\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h5 class=\"card-title\">Dogvilla</h5>\r\n");
      out.write("\t\t\t\t<p class=\"font-weight-bold\">Marca: Ferplast.</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t- Indicado para cães. <br>- Proporciona mais conforto ao pet.\r\n");
      out.write("\t\t\t\t\t<br>- Conta com abertura lateral que se torna uma rampa. <br>-\r\n");
      out.write("\t\t\t\t\tFácil de montar e higienizar. <br>- Disponível nos tamanhos P,\r\n");
      out.write("\t\t\t\t\tM e G.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<h5 class=\"font-weight-bold\" style=\"color: rgb(195, 93, 36)\">R$1.431,00</h5>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"btn btn-primary\">Comprar</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t<img class=\"card-img-top\" src=\"imagens/Casinha2-01.png\"\r\n");
      out.write("\t\t\t\talt=\"Imagem de capa do card\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h5 class=\"card-title\">Viveiro telhadinho duplex</h5>\r\n");
      out.write("\t\t\t\t<p class=\"font-weight-bold\">Marca: Bragança.</p>\r\n");
      out.write("\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t- Indicado para Calopsitas e pássaros semelhantes. <br>- Ideal\r\n");
      out.write("\t\t\t\t\tpara o conforto e qualidade de vida do seu amigo. <br>-\r\n");
      out.write("\t\t\t\t\tAcompanha comedouro, aba e poleiro de madeira. <br>- Está\r\n");
      out.write("\t\t\t\t\tacoplado a uma bandeja plástica. <br>- Possui rodinhas, o que\r\n");
      out.write("\t\t\t\t\tfacilita o transporte.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<h5 class=\"font-weight-bold\" style=\"color: rgb(195, 93, 36)\">R$220,00</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"btn btn-primary\">Comprar</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t<img class=\"card-img-top\" src=\"imagens/Casinha3-01.png\"\r\n");
      out.write("\t\t\t\talt=\"Imagem de capa do card\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h5 class=\"card-title\">Aquário curvo TL 550 128 litros</h5>\r\n");
      out.write("\t\t\t\t<p class=\"font-weight-bold\">Marca: Boyu</p>\r\n");
      out.write("\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t- Indicado para peixes. <br>- Perfeito para quem deseja ter um\r\n");
      out.write("\t\t\t\t\taquário marinho. <br>- Feito de vidro curvo. <br>- Mais\r\n");
      out.write("\t\t\t\t\tsegurança e espaço para seus pets. <br>- Disponível em 110V e\r\n");
      out.write("\t\t\t\t\t220V.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<h5 class=\"font-weight-bold\" style=\"color: rgb(195, 93, 36)\">R$3.620,99</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"btn btn-primary\">Comprar</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<!-- Título de produto 5 -->\r\n");
      out.write("\t<div class=\"menu-produto\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<H3>Coleiras</H3>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Adicionar produtos -->\r\n");
      out.write("\t<div class=\"card-deck\">\r\n");
      out.write("\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t<img class=\"card-img-top\" src=\"imagens/Coleira1-01.png\"\r\n");
      out.write("\t\t\t\talt=\"Imagem de capa do card\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h5 class=\"card-title\">Guia Flippy Regular</h5>\r\n");
      out.write("\t\t\t\t<p class=\"font-weight-bold\">Marca: Ferplast.</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t- Indicado para cães. <br>- Guia automática retrátil. <br>-\r\n");
      out.write("\t\t\t\t\tProporciona mais segurança e liberdade durante o passeio. <br>-\r\n");
      out.write("\t\t\t\t\tO fio pode ser extenso até 5 metros. <br>- Modelo ergonômico e\r\n");
      out.write("\t\t\t\t\tmoderno.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<h5 class=\"font-weight-bold\" style=\"color: rgb(195, 93, 36)\">R$69,99</h5>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"btn btn-primary\">Comprar</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t<img class=\"card-img-top\" src=\"imagens/Coleira2-01.png\"\r\n");
      out.write("\t\t\t\talt=\"Imagem de capa do card\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h5 class=\"card-title\">Peitoral Cat Neo Tattoo Marinheiro</h5>\r\n");
      out.write("\t\t\t\t<p class=\"font-weight-bold\">Marca: Tchucoo.</p>\r\n");
      out.write("\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t- Indicado para gatos. <br>- Regulável e super seguro. <br>-\r\n");
      out.write("\t\t\t\t\tFitas em poliéster antialérgico macias e confortáveis. <br>-\r\n");
      out.write("\t\t\t\t\tEstampas exclusivas. <br>- Argolas em metal e fecho em nylon.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<h5 class=\"font-weight-bold\" style=\"color: rgb(195, 93, 36)\">R$92,99</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"btn btn-primary\">Comprar</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t<img class=\"card-img-top\" src=\"imagens/Coleira3-01.png\"\r\n");
      out.write("\t\t\t\talt=\"Imagem de capa do card\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h5 class=\"card-title\">Peitoral Agila Fluo</h5>\r\n");
      out.write("\t\t\t\t<p class=\"font-weight-bold\">Marca: Ferplast</p>\r\n");
      out.write("\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t- Indicado para cães. <br>- Possui ótimo caimento e máximo\r\n");
      out.write("\t\t\t\t\tconforto. <br>- Oferece maior segurança para seu bichinho. <br>-\r\n");
      out.write("\t\t\t\t\tAjustável ao corpo do pet. <br>- Muito confortável e durável.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<h5 class=\"font-weight-bold\" style=\"color: rgb(195, 93, 36)\">R$139,99</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"btn btn-primary\">Comprar</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<!-- Título de produto 6 -->\r\n");
      out.write("\t<div class=\"menu-produto\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<H3>Roupinhas</H3>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Adicionar produtos -->\r\n");
      out.write("\t<div class=\"card-deck\">\r\n");
      out.write("\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t<img class=\"card-img-top\" src=\"imagens/Roupinha1-01.png\"\r\n");
      out.write("\t\t\t\talt=\"Imagem de capa do card\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h5 class=\"card-title\">Casaco com Capuz</h5>\r\n");
      out.write("\t\t\t\t<p class=\"font-weight-bold\">Marca: Urban Puppy.</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t- Indicado para cães. <br>- Estampa exclusiva. <br>-\r\n");
      out.write("\t\t\t\t\tModelagem ergonômica. <br>- Proporciona maior liberdade de\r\n");
      out.write("\t\t\t\t\tmovimentos. <br>- Disponível nos tamanhos 10, 12, 14.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<h5 class=\"font-weight-bold\" style=\"color: rgb(195, 93, 36)\">R$91,99</h5>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"btn btn-primary\">Comprar</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t<img class=\"card-img-top\" src=\"imagens/Roupinha2-01.png\"\r\n");
      out.write("\t\t\t\talt=\"Imagem de capa do card\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h5 class=\"card-title\">Casaco Moletom para Cachorro</h5>\r\n");
      out.write("\t\t\t\t<p class=\"font-weight-bold\">Marca: Urban Puppy.</p>\r\n");
      out.write("\t\t\t\t<p class=\"card-text\">- Casaco Moletom para Cachorro Mescla Azul\r\n");
      out.write("\t\t\t\t\tMarinho e Cinza Urban Puppy possui estampa em silk confeccionado em\r\n");
      out.write("\t\t\t\t\ttecido 97% algodão e 3% de poliéster. É confortável e quentinho seu\r\n");
      out.write("\t\t\t\t\tcachorrinho vai ficar protegido e estiloso nos dias mais frios.\r\n");
      out.write("\t\t\t\t<h5 class=\"font-weight-bold\" style=\"color: rgb(195, 93, 36)\">R$64,99</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"btn btn-primary\">Comprar</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t<img class=\"card-img-top\" src=\"imagens/Roupinha3-01.png\"\r\n");
      out.write("\t\t\t\talt=\"Imagem de capa do card\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h5 class=\"card-title\">Casaco Plush</h5>\r\n");
      out.write("\t\t\t\t<p class=\"font-weight-bold\">Marca: Urban Puppy</p>\r\n");
      out.write("\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t- Indicado para cães. <br>- Proporciona maior liberdade de\r\n");
      out.write("\t\t\t\t\tmovimentos. <br>- Estiloso e confortável. <br>-\r\n");
      out.write("\t\t\t\t\tProporciona maior liberdade de movimentos. <br>- Disponível\r\n");
      out.write("\t\t\t\t\tnos tamanhos 10, 12, 14, 16 e 18.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<h5 class=\"font-weight-bold\" style=\"color: rgb(195, 93, 36)\">R$85,99</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-primary\"\r\n");
      out.write("\t\t\t\t\tonclick=\"clickCounter('Casaco Plush','85.99')\">Comprar</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t<!--Redes sociais-->\r\n");
      out.write("\t<div class=\"container-fluid padding\">\r\n");
      out.write("\t\t<div class=\"row text-center padding\">\r\n");
      out.write("\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t<h2>Siga nossos perfis</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-12 social padding\">\r\n");
      out.write("\t\t\t\t<a href=\"#\"><i class=\"fab fa-facebook\"></i></a> <a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"fab fa-twitter\"></i></a> <a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"fab fa-instagram\"></i></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<!--Rodapé-->\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div class=\"container-fluid padding\">\r\n");
      out.write("\t\t\t<div class=\"row text-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t<img src=\"imagens/Logo.png\">\r\n");
      out.write("\t\t\t\t\t<hr class=\"light-1\">\r\n");
      out.write("\t\t\t\t\t<p>47-3456-9877</p>\r\n");
      out.write("\t\t\t\t\t<p>pegasus.pet@gmail.com</p>\r\n");
      out.write("\t\t\t\t\t<p>121, Antônio da Veiga</p>\r\n");
      out.write("\t\t\t\t\t<p>Blumenau - SC</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t<hr class=\"light-2\">\r\n");
      out.write("\t\t\t\t\t<h5>Atendimento</h5>\r\n");
      out.write("\t\t\t\t\t<hr class=\"light-3\">\r\n");
      out.write("\t\t\t\t\t<p>Segunda à sexta: 24 hrs</p>\r\n");
      out.write("\t\t\t\t\t<p>Sábados: 8 às 20 hrs</p>\r\n");
      out.write("\t\t\t\t\t<p>Domingos: Fechado</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t<hr class=\"light-4\">\r\n");
      out.write("\t\t\t\t\t<h5>Trabalhe conosco</h5>\r\n");
      out.write("\t\t\t\t\t<hr class=\"light-5\">\r\n");
      out.write("\t\t\t\t\t<p>Não há vagas disponíveis no momento.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t\t<hr class=\"light-6\">\r\n");
      out.write("\t\t\t\t\t<h5>&copy; pegasus.com</h5>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction AddCarrinho(produto, qtd, valor, posicao) {\r\n");
      out.write("\t\tlocalStorage.setItem(\"produto\" + posicao, produto);\r\n");
      out.write("\t\tlocalStorage.setItem(\"qtd\" + posicao, qtd);\r\n");
      out.write("\t\tvalor = valor * qtd;\r\n");
      out.write("\t\tlocalStorage.setItem(\"valor\" + posicao, valor);\r\n");
      out.write("\t\talert(\"Produto adicionado ao carrinho!\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
