/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.21
 * Generated at: 2019-07-09 14:56:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class BanhoEtosa_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/topo.jsp", Long.valueOf(1562684148109L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- JQuery -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"https://use.fontawesome.com/releases/v5.0.8/js/all.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Adicionar arquivo CSS externo -->\r\n");
      out.write("    <link href=\"estilos.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!--Ícone - Logo-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"favicon.ico.ico\" type=\"image/x-icon\" />\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("    \r\n");
      out.write("<body>\r\n");
      out.write("    <!--Cabeçalho-->\r\n");
      out.write("    <header class=\"menu-principal\">\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"header-1\">\r\n");
      out.write("                <div class=\"logo\">\r\n");
      out.write("                    <img src=\"imagens/logo-pegasus.png\" />\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("       \r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\r\n");
      out.write("            aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <!--Itens de navegação-->\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("            <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"index.jsp\">Início <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <!--Dropdown-->\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\"\r\n");
      out.write("                        data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                        Serviços</a>\r\n");
      out.write("                    <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"BanhoEtosa.jsp\">Banho e tosa</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\"\r\n");
      out.write("                        data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                        Produtos\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"alimento.jsp\">Alimentação</a>\r\n");
      out.write("                        <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"higiene.jsp\">Higiene</a>\r\n");
      out.write("                        <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"acessorio.jsp\">Acessórios</a>\r\n");
      out.write("                        <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"farmacia.jsp\">Farmácia</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <!--Fixos-->\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"CadastroCliente.jsp\">Cadastro <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#adocao\">Adoção <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"avaliacao.html\">Avaliação <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#quemsomos\">Quem somos? <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#contato\">Contato <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");

try{
		
		//Obter a mensagem
		String mensagem = request.getParameter("mensagem");
	
		//Tipos de mensagem
		switch(mensagem){
			case "falhaLogin":
				out.print("<div class='mensagem'>Usuário ou senha incorretos</div>");
			break;
			case "falhaSessao":
				out.print("<div class='mensagem'>Realize o login</div>");
			break;
		}
	}catch(Exception erro){}
	


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- PopUp -->\r\n");
      out.write("\r\n");
      out.write("<button class=\"btn btn-secondary my-2 my-sm-0\"\r\n");
      out.write("                    onclick=\"document.getElementById('modal-wrapper').style.display='block'\"\r\n");
      out.write("                    style=\"width:200px; margin-top:200px; margin-left:160px;\"><i class=\"fas fa-user\"></i>\r\n");
      out.write("                    Fazer login</i></button>\r\n");
      out.write("                   \r\n");
      out.write("\r\n");
      out.write("                <div id=\"modal-wrapper\" class=\"modal\">\r\n");
      out.write("\r\n");
      out.write("                    <form class=\"modal-content animate\" action=\"/action_page.php\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"imgcontainer\">\r\n");
      out.write("                            <span onclick=\"document.getElementById('modal-wrapper').style.display='none'\" class=\"close\"\r\n");
      out.write("                                title=\"Fechar PopUp\">×</span>\r\n");
      out.write("                            <img src=\"img/icone.jfif    \" alt=\"Avatar\" class=\"avatar\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\"Nome de usuário\" name=\"uname\">\r\n");
      out.write("                            <input type=\"password\" placeholder=\"Senha\" name=\"psw\">\r\n");
      out.write("                            <button type=\"submit\">Login</button>\r\n");
      out.write("                            <input type=\"checkbox\" style=\"margin:26px 30px;\"> Remember me\r\n");
      out.write("                            <a href=\"#\"\r\n");
      out.write("                                style=\"text-decoration:none; float:right; margin-right:34px; margin-top:26px;\">Esqueceu a senha?</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("<script>\r\n");
      out.write(" // If user clicks anywhere outside of the modal, Modal will close\r\n");
      out.write("\r\n");
      out.write("    var modal = document.getElementById('modal-wrapper');\r\n");
      out.write("    window.onclick = function (event) {\r\n");
      out.write("        if (event.target == modal) {\r\n");
      out.write("            modal.style.display = \"none\";\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Pegasus - Banho e Tosa</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- JQuery -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- Adicionar arquivo CSS externo -->\r\n");
      out.write("    <link href=\"estilosBanhoEtosa.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!--Ícone - Logo-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"favicon.ico.ico\" type=\"image/x-icon\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- JS -->\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!--Cabeçalho-->\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Título-->\r\n");
      out.write("    <div class=\"menu-banhotosa\">\r\n");
      out.write("        <br>\r\n");
      out.write("        <H3>Banho e tosa</H3>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Adicionar produtos - Banho e tosa -->\r\n");
      out.write("    <div class=\"card-deck\">\r\n");
      out.write("        <!--Produto 1-->\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <img class=\"card-img-top\" src=\"imagens/banhoetosa2.jpg\" alt=\"Imagem de capa do card\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <h5 class=\"card-title\">Banho</h5>\r\n");
      out.write("                <p class=\"font-weight-bold\">Banho sem tosa</p>\r\n");
      out.write("                <p> <br>- Remoção do mau cheiro e prevenção de doenças.\r\n");
      out.write("                    <br>- Manutenção da integridade da pele.\r\n");
      out.write("                    <br>- Temperatura da água testada e aprovada.\r\n");
      out.write("                    <br>- Secagem 100% efetiva.\r\n");
      out.write("                </p>\r\n");
      out.write("            <!-- Divisão -->\r\n");
      out.write("            <hr>\r\n");
      out.write("                <form>\r\n");
      out.write("                    <fieldset>\r\n");
      out.write("\r\n");
      out.write("                        <legend id=\"choice\" >Escolha o tamanho do seu animal:</legend>\r\n");
      out.write("\r\n");
      out.write("                        <input type=\"radio\" name=\"curso\">\r\n");
      out.write("                        <label>Até 45Kg</label>\r\n");
      out.write("\r\n");
      out.write("                        <input type=\"radio\" name=\"curso\">\r\n");
      out.write("                        <label>Acima de 45Kg</label>\r\n");
      out.write("                    </fieldset>\r\n");
      out.write("                </form>\r\n");
      out.write("            <!-- Divisão -->\r\n");
      out.write("            <hr>\r\n");
      out.write("                <form>\r\n");
      out.write("                    <label id=\"choice\"> Adicionar serviço delivery do animal?(+ R$ 30,00)</label>\r\n");
      out.write("                    <select required>\r\n");
      out.write("                        <option>Sim</option>\r\n");
      out.write("                        <option>Não</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </form>\r\n");
      out.write("            <!-- Divisão -->\r\n");
      out.write("            <hr>\r\n");
      out.write("                <h5 class=\"font-weight-bold\" style=\"color: rgb(195, 93, 36)\">Total: R$35,00</h5>\r\n");
      out.write("            <!-- Divisão -->\r\n");
      out.write("            <hr>\r\n");
      out.write("            <form>\r\n");
      out.write("                <p class=\"font-weight-bold\">Agendar</p>\r\n");
      out.write("                <br>Informe a data:\r\n");
      out.write("                <input id=\"dateAndTime\" type=\"date\" required>\r\n");
      out.write("\r\n");
      out.write("                <br>Informe horário:\r\n");
      out.write("                <input id=\"dateAndTime\" type=\"time\" id=\"appt\" min=\"8:00\" max=\"18:00\" required>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"font-weight-bold\">Obs.: A equipe entrará em contato por e-mail/telefone caso não haja\r\n");
      out.write("                    possibilidade de atendimento\r\n");
      out.write("                    na data e horário preteridos.\r\n");
      out.write("                </p>\r\n");
      out.write("            </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Divisão -->\r\n");
      out.write("            <hr>\r\n");
      out.write("            <div class=\"card-footer\">\r\n");
      out.write("                <a href=\"#\" class=\"btn btn-primary\">Comprar</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!--Produto 2-->\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("        <img class=\"card-img-top\" src=\"imagens/banhoetosa3.jpg\" alt=\"Imagem de capa do card\">\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <h5 class=\"card-title\">Banho e tosa</h5>\r\n");
      out.write("            <p class=\"font-weight-bold\">Máquina, tesoura, higiência, bebê</p>\r\n");
      out.write("            <p> <br>- Tosa específica para tipo de animal e escolha do cliente.\r\n");
      out.write("                <br>- Remoção do mau cheiro e prevenção de doenças.\r\n");
      out.write("                <br>- Manutenção da integridade da pele.\r\n");
      out.write("                <br>- Temperatura da água testada e aprovada.\r\n");
      out.write("                <br>- Secagem 100% efetiva.\r\n");
      out.write("            </p>\r\n");
      out.write("        <!-- Divisão -->\r\n");
      out.write("        <hr>\r\n");
      out.write("            <form>\r\n");
      out.write("                <fieldset>\r\n");
      out.write("\r\n");
      out.write("                    <legend id=\"choice\" >Escolha o tamanho do seu animal:</legend>\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"radio\" name=\"curso\">\r\n");
      out.write("                    <label>Até 45Kg</label>\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"radio\" name=\"curso\">\r\n");
      out.write("                    <label>Acima de 45Kg</label>\r\n");
      out.write("                </fieldset>\r\n");
      out.write("            </form>\r\n");
      out.write("            <!-- Divisão -->\r\n");
      out.write("        <hr>\r\n");
      out.write("        <form>\r\n");
      out.write("            <fieldset>\r\n");
      out.write("                <legend id=\"choice\" >Escolha o tipo de tosa:</legend>\r\n");
      out.write("\r\n");
      out.write("                <input type=\"radio\" name=\"curso\">\r\n");
      out.write("                <label>Máquina</label>\r\n");
      out.write("\r\n");
      out.write("                <input type=\"radio\" name=\"curso\">\r\n");
      out.write("                <label>Tesoura</label>\r\n");
      out.write("\r\n");
      out.write("                <input type=\"radio\" name=\"curso\">\r\n");
      out.write("                <label>Higiênica</label>\r\n");
      out.write("\r\n");
      out.write("                <input type=\"radio\" name=\"curso\">\r\n");
      out.write("                <label>Bebê</label>\r\n");
      out.write("            </fieldset>\r\n");
      out.write("        </form>\r\n");
      out.write("        <!-- Divisão -->\r\n");
      out.write("        <hr>\r\n");
      out.write("            <form>\r\n");
      out.write("                <label id=\"choice\">Adicionar serviço delivery do animal?(+ R$ 30,00)</label>\r\n");
      out.write("                <select required>\r\n");
      out.write("                    <option>Sim</option>\r\n");
      out.write("                    <option>Não</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </form>\r\n");
      out.write("        <!-- Divisão -->\r\n");
      out.write("        <hr>\r\n");
      out.write("            <h5 class=\"font-weight-bold\" style=\"color: rgb(195, 93, 36)\">Total: R$45,00</h5>\r\n");
      out.write("        <!-- Divisão -->\r\n");
      out.write("        <hr>\r\n");
      out.write("        <form>\r\n");
      out.write("            <p class=\"font-weight-bold\">Agendar</p>\r\n");
      out.write("            <br>Informe a data:\r\n");
      out.write("            <input id=\"dateAndTime\" type=\"date\" required>\r\n");
      out.write("\r\n");
      out.write("            <br>Informe horário:\r\n");
      out.write("            <input id=\"dateAndTime\" type=\"time\" id=\"appt\" min=\"8:00\" max=\"18:00\" required>\r\n");
      out.write("\r\n");
      out.write("            <p class=\"font-weight-bold\">Obs.: A equipe entrará em contato por e-mail/telefone caso não haja\r\n");
      out.write("                possibilidade de atendimento\r\n");
      out.write("                na data e horário preteridos.\r\n");
      out.write("            </p>\r\n");
      out.write("        </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Divisão -->\r\n");
      out.write("        <hr>\r\n");
      out.write("        <div class=\"card-footer\">\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-primary\">Comprar</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    <!--Rodapé-->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div id=\"contato\" class=\"container-fluid padding\">\r\n");
      out.write("            <div class=\"row text-center\">\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <img src=\"imagens/logo-pegasus.png\">\r\n");
      out.write("                    <hr class=\"light-1\">\r\n");
      out.write("                    <p>47-3456-9877</p>\r\n");
      out.write("                    <p>pegasus.pet@gmail.com</p>\r\n");
      out.write("                    <p>121, Antônio da Veiga</p>\r\n");
      out.write("                    <p>Blumenau - SC</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <hr class=\"light-2\">\r\n");
      out.write("                    <h5>Atendimento</h5>\r\n");
      out.write("                    <hr class=\"light-3\">\r\n");
      out.write("                    <p>Segunda à sexta: 24 hrs</p>\r\n");
      out.write("                    <p>Sábados: 8 às 20 hrs</p>\r\n");
      out.write("                    <p>Domingos: Fechado</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <hr class=\"light-4\">\r\n");
      out.write("                    <h5>Trabalhe conosco</h5>\r\n");
      out.write("                    <hr class=\"light-5\">\r\n");
      out.write("                    <p>Não há vagas disponíveis no momento.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <hr class=\"light-6\">\r\n");
      out.write("                    <h5>&copy; pegasus.com</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
