/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.21
 * Generated at: 2019-07-10 13:13:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CadastroCliente_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Pegasus Cadastro</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- JQuery -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Adicionar arquivo CSS externo -->\r\n");
      out.write("    <link href=\"estilos.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!--Ícone - Logo-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"favicon.ico.ico\" type=\"image/x-icon\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- JS -->\r\n");
      out.write("<script>\r\n");
      out.write("    //Máscara CEP\r\n");
      out.write("    function fMasc(objeto, mascara) {\r\n");
      out.write("        obj = objeto\r\n");
      out.write("        masc = mascara\r\n");
      out.write("        setTimeout(\"fMascEx()\", 1)\r\n");
      out.write("    }\r\n");
      out.write("    function fMascEx() {\r\n");
      out.write("        obj.value = masc(obj.value)\r\n");
      out.write("    }\r\n");
      out.write("    function mCEP(cep) {\r\n");
      out.write("        cep = cep.replace(/\\D/g, \"\")\r\n");
      out.write("        cep = cep.replace(/^(\\d{5})(\\d)/, \"$1-$2\")\r\n");
      out.write("\r\n");
      out.write("        return cep\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    //Máscara Telefone\r\n");
      out.write("    function fMascTelefone(objeto, mascara) {\r\n");
      out.write("        obj = objeto\r\n");
      out.write("        masc = mascara\r\n");
      out.write("        setTimeout(\"fMascEx2()\", 1)\r\n");
      out.write("    }\r\n");
      out.write("    function fMascEx2() {\r\n");
      out.write("        obj.value = masc(obj.value)\r\n");
      out.write("    }\r\n");
      out.write("    function mTelefone(telefone) {\r\n");
      out.write("        telefone = telefone.replace(/\\D/g, \"\")\r\n");
      out.write("        telefone = telefone.replace(/(\\d{2})(\\d)/, \"$1-$2\");\r\n");
      out.write("        telefone = telefone.replace(/(\\d{5})(\\d)/, \"$1-$2\");\r\n");
      out.write("\r\n");
      out.write("        return telefone\r\n");
      out.write("    }\r\n");
      out.write("    //Validar senha\r\n");
      out.write("    function validarSenha() {\r\n");
      out.write("        senha1 = document.f1.senha1.value\r\n");
      out.write("        senha2 = document.f1.senha2.value\r\n");
      out.write("\r\n");
      out.write("        if (senha1 == senha2)\r\n");
      out.write("            null\r\n");
      out.write("        else\r\n");
      out.write("            alert(\"SENHAS DIFERENTES\")\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!--Cabeçalho-->\r\n");
      out.write("    <header class=\"menu-principal\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"header-1\">\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <img src=\"imagens/logo-pegasus.png\" />\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--Formulário de cadastro-->\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("        <div class=\"form-container\">\r\n");
      out.write("            <span class=\"form-heading\">Cadastre-se</span>\r\n");
      out.write("            <form id=\"form-cadastro\" action=\"requisicoes/Cadastro.jsp\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <i id=\"user-form\" class=\"fas fa-user\"></i>\r\n");
      out.write("                    <input type=\"text\" placeholder=\"Nome completo...\" name=\"nome\" required>\r\n");
      out.write("                    <span class=\"bar\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <i id=\"email-form\" class=\"fas fa-envelope\"></i>\r\n");
      out.write("                    <input type=\"email\" placeholder=\"Email...\" name=\"email\" required>\r\n");
      out.write("                    <span class=\"bar\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <i id=\"adress-form\" class=\"fas fa-map-marker-alt\"></i>\r\n");
      out.write("                    <input type=\"text\" placeholder=\"Rua\" name=\"rua\" required>\r\n");
      out.write("                    <span class=\"bar\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <i id=\"adress-form\" class=\"fas fa-map-marker-alt\"></i>\r\n");
      out.write("                    <input type=\"text\" placeholder=\"Bairro\" name=\"bairro\" required>\r\n");
      out.write("                    <span class=\"bar\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <i id=\"adress-form\" class=\"fas fa-map-marker-alt\"></i>\r\n");
      out.write("                    <input type=\"text\" placeholder=\"Nº\" name=\"numero\" required>\r\n");
      out.write("                    <span class=\"bar\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <i id=\"adress-form\" class=\"fas fa-map-marker-alt\"></i>\r\n");
      out.write("                    <input type=\"text\" placeholder=\"Cidade\" name=\"cidade\" required>\r\n");
      out.write("                    <span class=\"bar\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <i id=\"adress-form\" class=\"fas fa-map-marker-alt\"></i>\r\n");
      out.write("                    <input type=\"text\" placeholder=\"Estado\" name=\"estado\" required>\r\n");
      out.write("                    <span class=\"bar\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <i id=\"cep-form\" class=\"fas fa-home\"></i>\r\n");
      out.write("                    <input type=\"text\" name=\"cep\" placeholder=\"CEP Ex.:#####-###\"\r\n");
      out.write("                        onkeydown=\"javascript: fMasc( this, mCEP );\" maxlength=\"9\" required >\r\n");
      out.write("                    <span class=\"bar\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <i id=\"phone-form\" class=\"fas fa-mobile-alt\"></i>\r\n");
      out.write("                    <input type=\"text\" placeholder=\"Telefone...\" name=\"telefone\"\r\n");
      out.write("                    onkeydown=\"javascript: fMascTelefone( this, mTelefone );\" maxlength=\"13\" required>\r\n");
      out.write("                    <span class=\"bar\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <i id=\"password-form\" class=\"fas fa-lock\"></i>\r\n");
      out.write("                    <input type=\"password\" placeholder=\"Senha...\" name=\"senha1\" size=\"20\" required>\r\n");
      out.write("                    <span class=\"bar\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <i id=\"confirm-form\" class=\"fas fa-lock\"></i>\r\n");
      out.write("                    <input type=\"password\" placeholder=\"Confirmar senha...\" name=\"senha2\" size=\"20\" required>\r\n");
      out.write("                    <span class=\"bar\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <button onclick=\"validarSenha()\">\r\n");
      out.write("                        <i id=\"send-form\" class=\"fab fa-telegram-plane\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"switch-login\">\r\n");
      out.write("                    <a href=\"#logar\">Já tem uma conta? <span>Login</span></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!--Rodapé-->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div id=\"contato\" class=\"container-fluid padding\">\r\n");
      out.write("            <div class=\"row text-center\">\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <img src=\"imagens/logo-pegasus.png\">\r\n");
      out.write("                    <hr class=\"light-1\">\r\n");
      out.write("                    <p>47-3456-9877</p>\r\n");
      out.write("                    <p>pegasus.pet@gmail.com</p>\r\n");
      out.write("                    <p>121, Antônio da Veiga</p>\r\n");
      out.write("                    <p>Blumenau - SC</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <hr class=\"light-2\">\r\n");
      out.write("                    <h5>Atendimento</h5>\r\n");
      out.write("                    <hr class=\"light-3\">\r\n");
      out.write("                    <p>Segunda à sexta: 24 hrs</p>\r\n");
      out.write("                    <p>Sábados: 8 às 20 hrs</p>\r\n");
      out.write("                    <p>Domingos: Fechado</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <hr class=\"light-4\">\r\n");
      out.write("                    <h5>Trabalhe conosco</h5>\r\n");
      out.write("                    <hr class=\"light-5\">\r\n");
      out.write("                    <p>Não há vagas disponíveis no momento.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <hr class=\"light-6\">\r\n");
      out.write("                    <h5>&copy; pegasus.com</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
