/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.21
 * Generated at: 2019-07-09 12:39:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/topo.jsp", Long.valueOf(1562675119473L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- JQuery -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"https://use.fontawesome.com/releases/v5.0.8/js/all.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Adicionar arquivo CSS externo -->\r\n");
      out.write("    <link href=\"estilos.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!--Ícone - Logo-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"favicon.ico.ico\" type=\"image/x-icon\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!--Cabeçalho-->\r\n");
      out.write("    <header class=\"menu-principal\">\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"header-1\">\r\n");
      out.write("                <div class=\"logo\">\r\n");
      out.write("                    <img src=\"imagens/logo-pegasus.png\" />\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("       \r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\r\n");
      out.write("            aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <!--Itens de navegação-->\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("            <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"index.jsp\">Início <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <!--Dropdown-->\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\"\r\n");
      out.write("                        data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                        Serviços</a>\r\n");
      out.write("                    <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"BanhoEtosa.jsp\">Banho e tosa</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\"\r\n");
      out.write("                        data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                        Produtos\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"alimento.jsp\">Alimentação</a>\r\n");
      out.write("                        <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"higiene.jsp\">Higiene</a>\r\n");
      out.write("                        <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"acessorio.jsp\">Acessórios</a>\r\n");
      out.write("                        <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                        <a class=\"dropdown-item\" href=\"farmacia.jsp\">Farmácia</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <!--Fixos-->\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"CadastroCliente.jsp\">Cadastro <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#adocao\">Adoção <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"avaliacao.html\">Avaliação <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#quemsomos\">Quem somos? <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#contato\">Contato <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");

try{
		
		//Obter a mensagem
		String mensagem = request.getParameter("mensagem");
	
		//Tipos de mensagem
		switch(mensagem){
			case "falhaLogin":
				out.print("<div class='mensagem'>Usuário ou senha incorretos</div>");
			break;
			case "falhaSessao":
				out.print("<div class='mensagem'>Realize o login</div>");
			break;
		}
	}catch(Exception erro){}
	
if(session.getAttribute("usuario") == null){

	
      out.write("\r\n");
      out.write("            <!--Formulário de login-->\r\n");
      out.write("            <form class=\"form-inline my-2 my-lg-0\" id=\"logar\" action=\"requisicoes/login.jsp\">\r\n");
      out.write("                <i class=\"fas fa-user\"></i>\r\n");
      out.write("                <input class=\"form-control mr-sm-2\" type=\"email\" placeholder=\"E-mail...\" name=\"email\">\r\n");
      out.write("                <input class=\"form-control mr-sm-2\" type=\"password\" placeholder=\"Senha...\" name=\"senha\">\r\n");
      out.write("                <button class=\"btn btn-primary my-2 my-sm-0\" type=\"submit\">Entrar</button>\r\n");
      out.write("           </form>\r\n");

}else{

      out.write("\r\n");
      out.write("\t\t\t<a href=\"requisicoes/sair.jsp\">Sair</a>\r\n");

}

      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Pegasus - Página Inicial</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- JQuery -->\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    <!-- Adicionar arquivo CSS externo -->\r\n");
      out.write("    <link href=\"estilos.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!--Ícone - Logo-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"favicon.ico.ico\" type=\"image/x-icon\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- JS -->\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("    <!--Banner-->\r\n");
      out.write("    <div id=\"slides\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("        <ul class=\"carousel-indicators\">\r\n");
      out.write("            <li data-target=\"#slides\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("            <li data-target=\"#slides\" data-slide-to=\"1\"></li>\r\n");
      out.write("            <li data-target=\"#slides\" data-slide-to=\"2\"></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"carousel-inner\">\r\n");
      out.write("            <div class=\"carousel-item active\">\r\n");
      out.write("                <img src=\"imagens/banner-serviços.png\">\r\n");
      out.write("                <div class=\"carousel-caption\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <img src=\"imagens/banner-adocao.png\">\r\n");
      out.write("                <div class=\"carousel-caption\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <img src=\"imagens/banner-produtos.png\">\r\n");
      out.write("                <div class=\"carousel-caption\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!--Jumbotron-->\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row jumbotron\">\r\n");
      out.write("            <div class=\"col-xs-12 col-sm-12 col-md-9 col-lg-9 col-xl-10\">\r\n");
      out.write("                <p class=\"lead\">O banho é extremamente importante para saúde e higiene dos pets e é um hábito necessário\r\n");
      out.write("                    na rotina do seu bichinho.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xs-12 col-sm-12 col-md-3 col-lg-3 col-xl-2\">\r\n");
      out.write("                <a href=\"banhoEtosa.html\"><button type=\"button\" class=\"btn btn-outline-secondary btn-lg\">Ficar limpinho</button></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!--Sessão de boas-vindas-->\r\n");
      out.write("    <div class=\"container-fluid padding\">\r\n");
      out.write("        <div class=\"row welcome text-center\">\r\n");
      out.write("            <div class=\"col-12\">\r\n");
      out.write("                <h1 class=\"display-4\">Seja bem-vindo!</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <div class=\"col-12\">\r\n");
      out.write("                <p class=\"lead\">Damos as boas vindas à você, novo cliente. Desejamos oferecer o melhor serviço e\r\n");
      out.write("                    experiência, cuidando do seu Pet com carinho e respeito.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Sessão ícones (Produtos, serviços, cadastro-->\r\n");
      out.write("    <div class=\"container-fluid padding\">\r\n");
      out.write("        <div class=\"row text-center padding\">\r\n");
      out.write("            <div class=\"col-xs-12 col-sm-6 col-md-4\">\r\n");
      out.write("                <a href=\"#\"><i class=\"fas fa-shopping-cart\"></i></a>\r\n");
      out.write("                <h3>PRODUTOS</h3>\r\n");
      out.write("                <p>Coleiras, bebedouros, casinhas e muito mais!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xs-12 col-sm-6 col-md-4\">\r\n");
      out.write("                <a href=\"banhoEtosa.html\"><i class=\"fas fa-bath\"></i></a>\r\n");
      out.write("                <h3>SERVIÇOS</h3>\r\n");
      out.write("                <p>Seu Pet limpo e saudável!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm-12 col-md-4\">\r\n");
      out.write("                <a href=\"cadastro.html\"><i class=\"fas fa-user-plus\"></i></a>\r\n");
      out.write("                <h3>CADASTRE-SE</h3>\r\n");
      out.write("                <p>E aproveite nossos serviços personalizados!</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr class=\"my-4\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!--Sessão Quem somos? - 2 column-->\r\n");
      out.write("    <div id=\"quemsomos\" class=\"container-fluid padding\">\r\n");
      out.write("        <div class=\"row padding\">\r\n");
      out.write("            <div class=\"col-lg-6\">\r\n");
      out.write("                <h2>Quem somos?</h2>\r\n");
      out.write("                <p>O petshop Pegasus atua no ramo desde 2015, acreditando no cuidado com\r\n");
      out.write("                    excelência dos pets confiados aos nossos serviços. Mais que uma empresa,\r\n");
      out.write("                    somos uma família apaixonada por animais e temos consciência da importância\r\n");
      out.write("                    e valor destes para seus tutores.\r\n");
      out.write("                    Prezamos pela qualidade do atendimento, desde o momento da recepção em\r\n");
      out.write("                    nossa sede até a saída segura do seu animalzinho, através de uma equipe\r\n");
      out.write("                    qualificada e especializada.\r\n");
      out.write("                </p>\r\n");
      out.write("                <p>O nosso desejo é fornecer a melhor experiência possível.\r\n");
      out.write("                    Para isso contamos também com sua resposta aos nossos serviços.\r\n");
      out.write("                    Venha fazer parte da família Pegasus!\r\n");
      out.write("                </p>\r\n");
      out.write("                <br>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-6\">\r\n");
      out.write("                <img src=\"imagens/equipe1.jpg\" class=\"img-fluid\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <hr class=\"my-4\">\r\n");
      out.write("    <!--Sessão Adoção-->\r\n");
      out.write("    <div id=\"adocao\" class=\"container-fluid padding\">\r\n");
      out.write("        <div class=\"row welcome text-center\">\r\n");
      out.write("            <div class=\"col-12\">\r\n");
      out.write("                <h1 class=\"display-4\">Animais disponíveis para adoção</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <div class=\"col-12\">\r\n");
      out.write("                <p class=\"lead\">Dirija-se à sede para adotar um amigo.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!--Cartões sessão Adoção -->\r\n");
      out.write("    <div class=\"container-fluid padding\">\r\n");
      out.write("        <div class=\"row padding\">\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img class=\"card-img-top\" src=\"imagens/adocao-1.jpg\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h4 class=\"card-title\">Peralta</h4>\r\n");
      out.write("                        <p class=\"card-text\">\"Fui encontrado vagando pelo centro da cidade.\r\n");
      out.write("                            Sou muito alegre e brincalhão. Quero um lar para dividir minha felicidade.\"</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img class=\"card-img-top\" src=\"imagens/adocao-2.jpeg\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h4 class=\"card-title\">Baleia</h4>\r\n");
      out.write("                        <p class=\"card-text\">\"Me chamam de Baleia porque adoro brincar na água.\r\n");
      out.write("                            Quero fazer parte de uma família.\"</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <img class=\"card-img-top\" src=\"imagens/adocao-3.jpg\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h4 class=\"card-title\">Norman</h4>\r\n");
      out.write("                        <p class=\"card-text\">\"Sou muito calma e adoro um cafuné.\r\n");
      out.write("                            Já estou pronta para me aconchegar com meus futuros tutores.\"</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr class=\"my-4\">\r\n");
      out.write("\r\n");
      out.write("        <!--Sessão parceiros-->\r\n");
      out.write("        <div class=\"partner\">\r\n");
      out.write("            <h1 class=\"partner-1\">Parceiros</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card-mb-3\">\r\n");
      out.write("            <img src=\"imagens/parceiros.jpg\" class=\"card-img-top\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <h5 class=\"card-title\">Sítio Dona Lúcia</h5>\r\n");
      out.write("                <p class=\"card-text\">Temos parceria com o Sítio Dona Lúcia, que oferece abrigo para animais\r\n");
      out.write("                    abandonados e em necessidade. Faça parte dessa rede!\r\n");
      out.write("                </p>\r\n");
      out.write("                <p class=\"card-text\"><small class=\"text-muted\">A Pegasus não possui controle sobre as atividades\r\n");
      out.write("                        do Sítio.</small></p>\r\n");
      out.write("                <a href=\"https://www.facebook.com/sitiodonalucia/\"><button type=\"button\"\r\n");
      out.write("                        class=\"btn btn-outline-secondary btn-outline-secondary\">Visitar</button></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!--Redes sociais-->\r\n");
      out.write("    <div class=\"container-fluid padding\">\r\n");
      out.write("        <div class=\"row text-center padding\">\r\n");
      out.write("            <div class=\"col-12\">\r\n");
      out.write("                <h2>Siga nossos perfis</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-12 social padding\">\r\n");
      out.write("                <a href=\"https://www.facebook.com/pegauspetshop\"><i class=\"fab fa-facebook\"></i></a>\r\n");
      out.write("                <a href=\"https://twitter.com/PegasusPetshop\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                <a href=\"https://www.instagram.com/petshoppegasus2019/\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!--Rodapé-->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div id=\"contato\" class=\"container-fluid padding\">\r\n");
      out.write("            <div class=\"row text-center\">\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <img src=\"imagens/logo-pegasus.png\">\r\n");
      out.write("                    <hr class=\"light-1\">\r\n");
      out.write("                    <p>47-3456-9877</p>\r\n");
      out.write("                    <p>pegasus.pet@gmail.com</p>\r\n");
      out.write("                    <p>121, Antônio da Veiga</p>\r\n");
      out.write("                    <p>Blumenau - SC</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <hr class=\"light-2\">\r\n");
      out.write("                    <h5>Atendimento</h5>\r\n");
      out.write("                    <hr class=\"light-3\">\r\n");
      out.write("                    <p>Segunda à sexta: 24 hrs</p>\r\n");
      out.write("                    <p>Sábados: 8 às 20 hrs</p>\r\n");
      out.write("                    <p>Domingos: Fechado</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <hr class=\"light-4\">\r\n");
      out.write("                    <h5>Trabalhe conosco</h5>\r\n");
      out.write("                    <hr class=\"light-5\">\r\n");
      out.write("                    <p>Não há vagas disponíveis no momento.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <hr class=\"light-6\">\r\n");
      out.write("                    <h5>&copy; pegasus.com</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
